In [21]:
from sklearn.datasets import load_iris


In [22]:
iris = load_iris()

In [24]:
data = iris.data
target = iris.target

In [25]:
print("Primeres 10 mostres de les dades 'data':")
print(data[:10])

Primeres 10 mostres de les dades 'data':
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [26]:
print("Primeres 10 mostres de les dades 'target':")
print(target[:10])

Primeres 10 mostres de les dades 'target':
[0 0 0 0 0 0 0 0 0 0]


In [28]:
concatenated_array = np.concatenate((data, target.reshape(-1,1)), axis=1)



In [30]:
print("Els 5 primers registres del nou array:")
print(concatenated_array[:5])


Els 5 primers registres del nou array:
[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


In [32]:
# Calcular la mitjana de la longitud del sèpal
sepal_length_mean = np.mean(data[:, 0])

# Calcular la desviació estàndard de la longitud del sèpal
sepal_length_std = np.std(data[:, 0])

# Calcular la mitjana de la longitud del pètal
petal_length_mean = np.mean(data[:, 2])

# Calcular la desviació estàndard de la longitud del pètal
petal_length_std = np.std(data[:, 2])

# Mostrar els resultats amb dos decimals
print("Mitjana de la longitud del sèpal: {:.2f}".format(sepal_length_mean))
print("Desviació estàndard de la longitud del sèpal: {:.2f}".format(sepal_length_std))
print("Mitjana de la longitud del pètal: {:.2f}".format(petal_length_mean))
print("Desviació estàndard de la longitud del pètal: {:.2f}".format(petal_length_std))


Mitjana de la longitud del sèpal: 5.84
Desviació estàndard de la longitud del sèpal: 0.83
Mitjana de la longitud del pètal: 3.76
Desviació estàndard de la longitud del pètal: 1.76


In [3]:
# Seleccionar una mostra aleatòria de 20 registres
random_sample = np.random.choice(concatenated_array, size=20, )

# Mostrar la mostra aleatòria seleccionada
print("Mostra aleatòria de 20 registres:")
print(random_sample)


ValueError: a must be 1-dimensional

In [7]:
import numpy as np
from sklearn.datasets import load_iris

# Carregar el conjunt de dades Iris
iris = load_iris()

# Carregar les dades "data" i "target"
data = iris.data
target = iris.target

# Concatenar les dades "data" i "target" en un nou array
concatenated_array = np.concatenate((data, target.reshape(-1,1)), axis=1)

# Crear una matriu buida per emmagatzemar els resultats
result_matrix = np.zeros((3, 4))

# Calcular la mitjana i desviació estàndard de cada característica per espècie
for i in range(3):
    species_data = concatenated_array[concatenated_array[:, -1] == i, :-1]
    result_matrix[i, :] = np.concatenate((np.mean(species_data, axis=0), np.std(species_data, axis=0)))

# Mostrar la matriu amb les mitjanes i desviacions estàndard per espècie
print("Matriu amb la mitjana i desviació estàndard per espècie:")
print(result_matrix)

ValueError: could not broadcast input array from shape (8,) into shape (4,)

In [8]:
# Trobar l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"
max_index = np.argmax(np.mean(data[:, 0].reshape(-1, 1), axis=0) * (target == 0).sum())

# Mostrar l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"
print("L'espècie amb el valor màxim mitjana de la variable 'sepal length (cm)' és:", iris.target_names[max_index])

L'espècie amb el valor màxim mitjana de la variable 'sepal length (cm)' és: setosa


In [9]:
# Trobar la mostra amb els pètals més llargs
max_index = np.argmax(data[:, 2])

# Mostrar la mostra amb els pètals més llargs
print("La mostra amb els pètals més llargs:")
print(data[max_index])

La mostra amb els pètals més llargs:
[7.7 2.6 6.9 2.3]
